// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/apps/store-api/prisma/schema.prisma",
  migrations: {
    path: "src/apps/store-api/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    shadowDatabaseUrl: "postgresql://postgres:Ismk7%40wscxSpjdbI@82.29.175.176:5467/postgres?schema=shadow",
  },
});
