module.exports = {
	addAdminNote: require("./addAdminNote"),
	confirmCartPurchase: require("./confirmCartPurchase"),
	createCartPurchase: require("./createCartPurchase"),
	deleteItemFromPurchase: require("./deleteItemFromPurchase"),
	deletePurchase: require("./deletePurchase"),
	getAllPurchases: require("./getAllPurchases"),
	getCartPurchaseById: require("./getCartPurchaseById"),
	getCartPurchases: require("./getCartPurchases"),
	getFullOrdersReport: require("./getFullOrdersReport"),
	getMonthlyConfirmedPurchasesCount: require("./getMonthlyConfirmedPurchasesCount"),
	getProductPurchaseStats: require("./getProductPurchaseStats"),
	getPurchaseStatistics: require("./getPurchaseStatistics"),
	getResponseTimeStatistics: require("./getResponseTimeStatistics"),
	receivePurchase: require("./receivePurchase"),
	returnCartPurchase: require("./returnCartPurchase"),
};
